name: covidpss
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  url_launcher: ^5.1.2
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/imran.png
    - assets/counsellor/
    - assets/precaution/
    - assets/symptoms/
    - assets/symptoms/o.png
    - assets/symptoms/p.png
    - assets/symptoms/s.png
    - assets/symptoms/st.png
    - assets/precaution/sanit.jpg
    - assets/precaution/mask.jpg
    - assets/precaution/distance.jpg
    - assets/precaution/crowd.jpg
    - assets/precaution/correct.jpg
    - assets/precaution/cov.jpg
    - assets/counsellor/aunty.png
    - assets/counsellor/bea.png
    - assets/counsellor/cast.png
    - assets/counsellor/image3.png
    - assets/counsellor/image5.png
    - assets/counsellor/image6.png
    - assets/counsellor/image7.png
    - assets/counsellor/images.png
    - assets/counsellor/img8.png
    - assets/Annotation.png
    - assets/Annotations.png
    - assets/Banners.jpg
    - assets/call.jpg
    - assets/Dr-Wasdev.jpeg
    - assets/faq.jpg
    - assets/Farhan-Malik.jpg
    - assets/goverment.png
    - assets/image.png
    - assets/image3.png
    - assets/image5.png
    - assets/images.png
    - assets/poster.png
    - assets/rehman.png
    - assets/sadaf.jpeg
    - assets/transparent.png
    - assets/Untitled.jpg
    - assets/warning.jpg
    - assets/boy.png
    - assets/webnar.jpg
    - assets/girl.png
    - assets/safe.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
